config/routes.rb
Rails.application.routes.draw do

  resources :units
  resources :furnitures
 devise_for :users

 get "/" => "units#home"
 get "/furnitures/category/:category" => "furnitures#category" 
 get "/furnitures/selected_items/show" => "furnitures#selected_items" 
 delete "/furnitures/selected_items/show" => "furnitures#destroy" 
 post "/furniture_location" => "furniture_units#furniture_location"
 get "/units/session/end" => "furniture_units#end_session"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/furniture.rb
class Furniture < ApplicationRecord
	has_many :furniture_units
	has_many :units, through: "furniture_units"
end

app/models/furniture_unit.rb
class FurnitureUnit < ApplicationRecord
	belongs_to :unit
  	belongs_to :furniture
  	belongs_to :user
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :furniture_units
	has_many :furnitures, through: "furniture_units"	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :furniture_units
  validates :name, presence: true
end

app/models/user_unit.rb
class UserUnit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/furniture_units_controller.rb
class FurnitureUnitsController < ApplicationController
	def furniture_location
		unit_id = params[:unit_id]
		user_id = params[:user_id]
		
		params[:furnitures].each do |key, value|

			furniture_id = value[:furniture_id]
			furniture_unit_id = value[:furniture_unit_id]
			top = value[:style_top]
			left = value[:style_left]

			if furniture_unit_id == nil
				the_image = Furniture.find(furniture_id).scaled_image
				FurnitureUnit.create!(unit_id: unit_id, user_id: user_id, furniture_id: furniture_id, top: top, left: left, image: the_image)

			else
				fu = FurnitureUnit.find(value[:furniture_unit_id])
				fu.update(top: value[:style_top] , left: value[:style_left])	
			end
		end
	end

	def end_session
		reset_session
		redirect_to "/"
    end

   
end

  

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController


	def category
		@list = Furniture.where(category: params[:category])
		if params[:store] !=nil  
			@list= @list.where(store: params[:store])
		elsif params[:color] !=nil 
			@list= @list.where(color: params[:color])
		elsif params[:store] !=nil && params[:color] !=nil
			@list= @list.where(store: params[:store]).where(color: params[:color])
		else
			@list.all
		end

		@unit = Unit.find_by(id: session[:my_floorplan])
	end

	def show
		@furniture = Furniture.find_by(id: params[:id])
	end

	def update
		the_id = params[:furniture][:furniture_id]
		(session[:saved_items] ||= []) << the_id
		the_furniture = Furniture.find(the_id).category

		furniture_list = self.all_furniture

		total_price=0
		furniture_list.each do |item|
  			total_price+= item.price
		end

		session[:total_price] = total_price

		redirect_to "/furnitures/category/#{the_furniture}"
	end

	def selected_items
		@furniture_list = self.all_furniture
		render :selected_items
	end

	def all_furniture
		@selected_items = session[:saved_items]
		furniture_list = []
		if @selected_items
			@selected_items.each do |x|
				furniture_list << Furniture.find(x.to_i)
			end
		end
		return furniture_list
	end

	def destroy
   		 the_furniture = furniture_list.find(params[:furniture_id])
   		 the_furniture.destroy

  	end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
	def home
		@current_floor_id = session[:my_floorplan].inspect
	end
	
	def show
		@unit = Unit.find_by(id: params[:id])
		if current_user
		@the_selected_furnitures = FurnitureUnit.where(unit_id: @unit.id).where(user_id: current_user.id) 
		else
		@the_selected_furnitures = FurnitureUnit.where(unit_id: @unit.id)
		end
		 session[:my_floorplan] ||= @unit.id
		 (session[:all_floorplans] ||= []) << @unit.id
		 @saved_items = []
		 if session[:saved_items]
		 session[:saved_items].each do |x|
		 one_furniture = Furniture.find(x)
		 @saved_items << one_furniture
		 end
		end


	end
	def index
		street_name = params[:street_name]
		street_number = params[:street_number]
		units = Unit.all
		@units = search(street_name, units)
	end


	private 

		def search(search_term, array)
 		newarray = []
   		 array.each do |x|
    		if x.street_name.downcase[search_term.downcase]
    		newarray << x
    		end
		end
		newarray
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furniture_units_helper.rb
module FurnitureUnitsHelper
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/furniture_units/reset_session.html.erb
<h3 class="Page-description" > Thank you </h3>

app/views/furnitures/category.html.erb
<h3 class="Page-description">Furniture selection</h3>
<br>

<p class= "sub-1">Categories</p>
<br>

<div class= Categories>
<button class="btn btn-lg btn-light"><a href="/furnitures/category/couch">Couch</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/armchair">Armchair</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/center-table">Side Table</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/dinner-table">Dinner Table</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/chair">Chair</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/bed">Bed</a></button> 
</div>

<!-- <form class= "Filter">
		<p>Filter by Store :</p>
		<label for="store"> Ikea </label>
        <input type="checkbox" name="store[]" value="Ikea">

        <label for="store"> Target</label>
        <input type="checkbox" name="store[]" value="Target">

        <label for="store"> Overstock </label>
        <input type="checkbox" name="store[]" value="Overstock">

        <button> Filter </button>
</form>

<form class= "Filter">

		<p>Filter by Color :</p>
		<label for="color"> Black </label>
        <input type="checkbox" name="color[]" value="Black">

        <label for="color"> Grey </label>
        <input type="checkbox" name="color[]" value="Grey">

        <label for="color"> Beige </label>
        <input type="checkbox" name="color[]" value="Beige">
        
        <button> Filter </button>
</form>
 -->
<!-- <div class= "Filter">
		<p>Filter by Price :</p>
		
</div> -->




	<% @list.each do |furniture| %>
		<div class="col-md-3">
			<div class="row">

<div class= "selection">
	<a href="/furnitures/<%=furniture.id%>">
		<div class= "Furniture_list">
			<img src="<%=furniture.store_image%>" height= 200px> <%=furniture.store%> / $<%=furniture.price%> 
		</div>
	</a>
</div>
</div>
</div>
	
	 	
	
	<% end %>

 		

app/views/furnitures/selected_items.html.erb
<h3 class="Page-description"> Saved Items </h3>
<br>
<br>

<div class= "cart-list">
<% if @furniture_list%>
  <% @furniture_list.each do |item| %>
    <ul>
      <img src= <%= item.store_image %> height = 80px> <%= link_to item.category, furniture_path(item) %> 
       - <%= item.store %> - <%= item.color %> -  $<%= item.price %> 
       <br>
   
    <%= link_to "Remove", furnitures_selected_items_show_path, method: "destroy" %>
     </ul>
  <% end %>
<% end%>
</div>

<br>
<div class= "total">
		<% if session[:total_price] %>
      <div class="total"><strong>Total: $<%= session[:total_price] %></strong>
      <% end %>
  </div>



 

app/views/furnitures/show.html.erb
<h3 class="Page-description"> Details </h3>

<br>

	<div class= "attributes">
 		<p> Brand: <%=@furniture.store%> </p>
	 	<p> Price: $ <%=@furniture.price%> </p>
	 	<p> Color: <%=@furniture.color%> </p>
	 	<p> Width: <%=@furniture.width%>" </p>
	 	<p> Length: <%=@furniture.lenght%>" </p>
	
<br>

<%= form_for @furniture do |f| %>
        <%= f.hidden_field :furniture_id, value: @furniture.id %>
        <%= f.submit "Select Item" %> 
<% end %> 

</div>
			<div class="image-deatil"> <img src =<%=@furniture.store_image%> height=600px </div>

	 	

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoveMeIn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



     <%if session[:my_floorplan] %>
     <div class="btn btn-light btn-lg pull-right toggle">
     <a href='/units/session/end'> End Session </a></div>
     <% end %>

    <div class="btn btn-light btn-lg pull-right toggle"><a href="/">Home</a></div>

      <% if session[:total_price] %>
      <div class="btn btn-light btn-lg pull-right toggle">
        <a href="/furnitures/selected_items/show"> Saved Items $<%= session[:total_price] %></a></div>
      <% end %>

     <%if session[:my_floorplan] %>
     <div class="btn btn-light btn-lg pull-right toggle">
     <a href='/furnitures/category/couch'> Furniture Selection </a></div>
     <% end %>

    <%if session[:my_floorplan] %>
    <div class="btn btn-light btn-lg pull-right toggle">
     <a href='/units/<%=session[:my_floorplan]%>'> My Floor Plan </a></div>
     <% end %>

    
   


     <div class="btn btn-light btn-lg pull-right toggle">
       <%if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %>
     <% else %>
    <%= link_to('Sign Up', new_user_registration_path)  %> 
     <% end %>
   </div>

     <div class="btn btn-light btn-lg pull-right toggle">
       <%if user_signed_in? %>
     <p > <%= current_user.name %>  </p>
   
     <% else %>
    <%= link_to('Login', new_user_session_path)  %> 
     <% end %>
   </div>



 
    <%= yield %>
  </body>
</html>



        </ul>
    </nav>

app/views/units/floorplan.html.erb
	 <img src= <%= @unit.floorplan %> >

app/views/units/home.html.erb
<header id="top" class="header">
        <div class="text-vertical-center">
            <h1> MoveMeIn </h1>

        
          
          <div class = "Home_Form">

          <form action="/units" method="GET">
          <div>
          <input type="text" name="street_name" id="street_name" placeholder="street name"required>
          </div>
          <div>
          <input type="number" name="street_number" id="street_number" placeholder="street number"required>
          </div>
          <div>
          <input type="text" name="city" id="city" placeholder="City"required>
          </div>
          <div>
          <input type="text" name="state" id="state" placeholder="State"required>
          </div>
          <div>
          <input type="text" name="zip_code" id="zip_code" placeholder="Zip"required>
          </div>
          <br>
           <button class = "btn btn-dark btn-lg" type=submit>Search Floorplan</button>
           <!--  <input type="hidden" name="authenticity_token"
            value="<%= form_authenticity_token %>"> -->
      </form>

   <!--    <h2><strong>Enter your address and start furnishing your new home</strong></h2> -->

      </div>

        
        </div>
    </header>

<div class = "Home_Page"> 



      
         

</div>

app/views/units/index.html.erb
<h3 class="Page-description">Units </h3>
<br>
<br>
<div class= "units">

	<% @units.each do |unit| %>
	<ul><%= link_to unit.unit_number, unit_path(unit) %></ul> 
<% end %>



</div>

app/views/units/show.html.erb
<style>
	#div2 {
		background-image: url("<%= @unit.floorplan %>");
		height: 600px;
		background-repeat: no-repeat;
		margin-left: 20%;
		margin-top: 50px
	}

	.draggable-thing {
		position: absolute;
	}
</style>

<h3 class="Page-description" > Layout </h3>


<div class="col-md-3">
	<div class= "Categories" data-id="<%=@unit.id%>" data-user-id="<%= current_user.id if user_signed_in? %>"> 
		<br>
	<br>
	<p class= "sub">Categories</p>
	<br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/couch">Couch</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/armchair">Armchair</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/center-table">Side Table</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/dinner-table">Dinner Table</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/chair">Chair</a></button> <br>
	<button class="btn btn-lg btn-light"><a href="/furnitures/category/bed">Bed</a></button> 
</div>
</div>



<div id= "div2" ondrop="drop(event)" ondragover="allowDrop(event)">
	<% @the_selected_furnitures.each_with_index do |x, index| %>


		<img src="<%=x.image%>" class="piece<%=index%>" draggable="true" class="draggable-thing" ondragstart="drag(event)" id="furniture-unit-<%= x.id %>" data-furniture_unit_id="<%= x.id %>">  
		<style>
		 .piece<%=index%>{
		 	position: absolute;
		 	top: <%=x.top%>;
		 	left: <%=x.left%>;
		}
		</style>


	<%end%>
</div> 


<button class ="js-save-layout"> Save Layout </button>

<p> Drag and Drop the items you selected </p>



<div id= "div1">
	<% if @saved_items.length != nil%>
		<% @saved_items.each_with_index do |x, index| %>
		 <img src="/images/SPACE.png" 
			<div id="#{index}" ondrop="drop(event)" ondragover="allowDrop(event)">
			  <img src="<%=x.scaled_image%>"
			  draggable="true" class="draggable-thing" ondragstart="drag(event)" id="<%= index + 100 %>" data-furniture_id="<%= x.id %>"> 
		<img src="/images/SPACE.png" 
		
			</div>
		
		<% end %>
	<%end%>
</div>


<script>
	
var data
var furniture 
var saved_coordinates = {};
var furniture_id 
var furniture_unit_id

	function allowDrop(ev) {
	    ev.preventDefault();
	};

	function drag(ev) {
	    ev.dataTransfer.setData("image", ev.target.id);
	};

	function drop(ev) {
	    ev.preventDefault();
	    data = ev.dataTransfer.getData("image");
	     furniture = document.getElementById(data);
	    ev.target.appendChild(furniture);

	    furniture.style.top = ev.clientY + "px";
	    furniture.style.left = ev.clientX + "px";

	   
	    furniture_id = $(furniture).data("furniture_id")
		furniture_unit_id = $(furniture).data("furniture_unit_id")

		if (furniture_id != undefined) {
			saved_coordinates[data] = { style_top: furniture.style.top, style_left: furniture.style.left, furniture_id: furniture_id } 
		};
		if (furniture_unit_id != undefined) {
			saved_coordinates[data] = { style_top: furniture.style.top, style_left: furniture.style.left, furniture_unit_id: furniture_unit_id } 
		};

		console.log(saved_coordinates );
	    
	};

		function saveLayout() {
	    	var apiData = { unit_id: $('.Categories').data("id"), furnitures: saved_coordinates, user_id:$('.Categories').data("user-id")  };

	    	console.log(apiData);

		if(saved_coordinates != null){ 
	    $.ajax({
			data: apiData,
			method: "POST",
			url: "/furniture_location",
			success: notifyUser
			});

		};

		function notifyUser () {
			console.log("it worked");
		}
	};

$(".js-save-layout").on("click", saveLayout);
	
</script>

app/views/users/new.html.erb
<div class="field">
	<%= f.label :name %> <br />
	<%= f.text_field :name, autofocus: true %>
</div>